# Please insert new items alphabetically.

backend-developers:
  members:
    - geuben
    - partsalliance
    - keirwl
    - NastyaVasilzhenko
    - Teh-Hamstah
    - andrewmwilson

  channel:
    "#developers"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP
    - "[DO NOT SEAL]"
    - "[DON'T SEAL]"
    - DO NOT SEAL
    - DON'T SEAL

  quotes:
    - Stop playing Pokemon Go and write some code!
