# Please insert new items alphabetically.

backend-developers:
  members:
    - andrewmwilson
    - geuben
    - jcalero
    - glebanatalia
    - csikosdiana
    - gee1jay1
    - krishnawhite
    - chutchut
    - partsalliance
    - keirwl

  channel:
    "#developers"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP
    - "[DO NOT SEAL]"
    - "[DON'T SEAL]"
    - DO NOT SEAL
    - DON'T SEAL

  quotes:
    - Stop playing Pokemon Go and write some code!
