# Please insert new items alphabetically.

backend-developers:
  members:
    - andrewwilson
    - geuben
    - jcalero
    - johtso
    - siminio

  channel:
    "#developers"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP
    - "[DO NOT SEAL]"
    - "[DON'T SEAL]"
    - DO NOT SEAL
    - DON'T SEAL

  quotes:
    - Stop playing Pokemon Go and write some code!
